server.port=9000
spring.application.name=api-gateway

# Service URLs
customer.service.url=http://localhost:8081
movie.service.url=http://localhost:8082
booking.service.url=http://localhost:8083

# JWT Secret (same as customer-service)
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
